// Напаўненне базы дадзенымі
create (g: Game {name: "The Sims 4", year: 2014, genre: "Life simulator"})
create (g: Game {name: "Spore", year: 2008, genre: "Life simulator"})
create (g: Game {name: "League of Legends", year: 2009, genre: "MOBA"})
create (g: Game {name: "Crazy Machines", year: 2005, genre: "Puzzle"})
create (g: Game {name: "Ферма Айрис", year: 2009, genre: "Business"})
create (g: Game {name: "Building & Co", year: 2008, genre: "Building simulator"})
create (g: Game {name: "Алекс Гордон",  year: 2009, genre: "Platformer"})
create (g: Game {name: "Гений обороны", year: 2010, genre: "Defense tower"})
create (g: Game {name: "5 карточных королевств", year: 2009, genre: "Logic"})